#!/bin/bash
vga_is=$([ -z $1 ] && echo above || echo $1)
if [ $vga_is == "off" ]; then
  xrandr --output VGA1 --off
else
  xrandr --output LVDS1 --auto;  xrandr --output VGA1 --auto; xrandr --output VGA1 --${vga_is} LVDS1
fi
