#!/usr/bin/env bash
vga_is=$([ -z $1 ] && echo above || echo $1)
if [ $vga_is == "off" ]; then
  xrandr --output HDMI1 --off
fi
if [ $vga_is == "except" ]; then
  xrandr --output eDPI1 --auto; xrandr --output HDMI1 --auto; xrandr --output eDPI1 --off
else
  xrandr --output eDPI1 --auto;  xrandr --output HDMI1 --auto; xrandr --output HDMI1 --${vga_is} eDPI1
fi
~/.fehbg 2>/dev/null
